### PR TITLE
V1.9 quickfix

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Based on our comment exchange in pull #60 I do not expect this to be merged in whole (although feel free to cherrypick the pom & plugin update commit). 

However, this addresses #59 via a work-around while we wait for Spigot to correct. Some of us, sadly, do not have the luxury of waiting for Spigot to address the issue that fixing, but also cannot safely disable WorldBorder within the Nether. Hence I'm placing this PR so that folks can build a workaround locally for their servers.

Here is a snippet of my investigation into the actual source of #59, which is not as was assumed incorrect player From within the teleportation event, but is rather an eventual consistency problem with the Player location in Bukkit. As a result, the cause of the problem becomes _WorldBorder itself_ since Spigot puts incorrect data in the Player object, causing the BorderCheckTask to "fix" the player's location during a regular update, causing the spurious second teleportation.

Again, the actual Bukkit-called events are totally fine -- To and From are 100% correct, always -- but the backing _Player_ data has inconsistent state tracking / eventual consistency problems. 

Illustration -- I run a separate plugin to help players avoid "trapped" netherportals, and I have it set up to spit out teleportation event data for debugging, currently:

Here is the original teleportation event; you can check the math, world is 8:1 standard nether, the original teleport event is correct:

```
[05:05:13] [Server thread/INFO]: [WorldBorder] Teleport cause: NETHER_PORTAL
[05:05:13] [Server thread/INFO]: [PortalFix] DeepCopy teleported from Location{world=CraftWorld{name=world},x=-8.189748678030902,y=68.24918707874468,z
=251.82862061288284,pitch=22.949966,yaw=-95.05548} to Location{world=CraftWorld{name=world_nether},x=0.0,y=70.0,z=28.0,pitch=22.949966,yaw=-95.05548}
with cause NETHER_PORTAL (cancelled? false)
```

You can also see that WorldBorder catches that event and sees no issue.

Then, a second later:

```
[05:05:14] [Server thread/WARN]: [WorldBorder] Border crossing in "world_nether". Border radius 200 at X: 1.6 Z: 27.7
[05:05:14] [Server thread/WARN]: [WorldBorder] Player position X: -8.2 Y: 68.2 Z: 251.8
[05:05:14] [Server thread/WARN]: [WorldBorder] New position in world "world_nether" at X: -7.5 Y: 68.0 Z: 224.5
[05:05:14] [Server thread/INFO]: [WorldBorder] Teleport cause: PLUGIN
[05:05:14] [Server thread/INFO]: [PortalFix] DeepCopy teleported from Location{world=CraftWorld{name=world_nether},x=-8.189748678030902,y=68.249187078
74468,z=251.82862061288284,pitch=22.949966,yaw=84.94452} to Location{world=CraftWorld{name=world_nether},x=-7.5,y=68.0,z=224.5,pitch=22.949966,yaw=84.
94452} with cause PLUGIN (cancelled? false)
```

WorldBorder now teleports the player to the _wrong_ location, during the per-second "checkPlayer" event, because of the player data inconsistency I have described.

Hope this helps. As with the prior, I'd be grateful if you left this PR open until Bukkit fixes, just so people can see a possible solution, but I do not expect it to be merged.

### CODE REVIEW

**Comment by Brettflan** [comment]
Thanks again for doing the research into what exactly is happening. If you haven't already, you might post your conclusions over in the relevant report(s) in the Spigot bugtracker, as I'm sure it would help them out.

**Comment by ProgrammerDan** [comment]
No problem, I was introduced to this plugin on Civcraft and use it on my own server as well -- it's an absolute lifesaver, thanks much for creating it :). I have updated the tracker, but I'm unclear if that issue has received any attention. I may need to simply create a new issue w/ the relevant investigative results.

Thanks again!

**Comment by cjucoder** [comment]
Thanks to ProgrammerDan for the workaround and also the excellent explanation and documentation here. It's helped me and my server.

**Comment by aikar** [comment]
FYI in future instead of a new PR, you can rebase edit the commit to remove the undesired change, then force push to update the existing PR.

Where does the 2nd action happen at?

Are 2 teleport events being fired? We can try to get it patched in Paper, but need some more description on chain of events and where the bug happens.

**Comment by ProgrammerDan** [comment]
@aikar When appropriate I do that, yes. In this case I felt it wasn't appropriate.

If you carefully read the description you will see that Bukkit only fires a single teleport event; both To and From are correct in that event.

However, for a few seconds after the teleport event has completed, the _Player_ object is inconsistent with the _correct_ location as listed in the teleport event.

As a consequence, WorldBorder _causes_ problems by incorrectly believing the player is outside world border (they are not) and issues teleport events until it is satisfied that the player is "back inside the world" .... even though the whole time, the player was, in fact, inside WB.

I hope that clears it up for you. There is nothing to patch with the _fired event_; the patch needs to occur somewhere deeper, to correct the length of time that the Player object's data is inconsistently reported vs. what was delivered via the Event's To field.

**Comment by Brettflan** [comment]
I don't really like the phrasing of "WorldBorder causes problems", when the source of the problem here is of course a bug in Spigot.

Let me try to provide more details on what is happening.

When a player is teleported between worlds (whether by portal or by a plugin or whatever), the Player object briefly contains mismatched and flat out incorrect Location data returned by getLocation(). The Location which is returned points to the current world (with location.getWorld()) that the player was just teleported to, while the X/Y/Z coordinates briefly get stuck on what they were in the original world when the teleport occurs. Since the coordinates in the previous world can easily be outside the border in the current world which the Location references, WorldBorder sees that and teleports them back inside the border from the incorrect coordinates.

If the World returned by the Location were not updated and pointed to the previous world just like the coordinates, the delay in them updating would actually not be that bad at all, but due to the mismatched world reference and coordinates you'll get problems in any plugin which relies on that data being correct.

I'd also like to point out that while your workaround should work for most cases since usually the method of teleporting between worlds is by portal, any other method which doesn't trigger a PlayerPortalEvent would not be handled by it. A fair number of plugins and mods provide other ways of moving between worlds.

**Comment by ProgrammerDan** [comment]
As the author I can appreciate your perspective. I did not mean to cause offense; but to be frank, the _problem_ as reported in the Spigot issue _and here_ completely misrepresented the actual problem because no-one bothered to investigate. The _effect_ that people were reporting as Spigot's problem was actually WorldBorder's periodic border guard function operating on the _actual_ bug -- yes, in Spigot -- which is the inconsistent data. 

Until and unless Spigot fixes that underlying issue, WorldBorder's behavior _does in fact_ become a regression, and the same would be for every other plugin using Spigot.

Hopefully the technique demonstrated here can suffice as a work-around for other plugins.

I never meant it to be a general purpose solution; it's one I researched and use for my personal server, and if other people can benefit, great. If not, that's their concern. 

As I stated up top in OP, this pull is not meant to be merged in.

-----

Just getting frustrated that people aren't bothering to read or comprehend what I wrote in the top post, and @Brettflan and I are having to waste time restating things. Again, @Brettflan, no offense meant. Just getting annoyed at people and mis-phrased in my reply.

**Comment by aikar** [comment]
I'm going to ignore the undeserved hostility of that reply. How it's worded was not very clear to me as I have zero experience with World Border, I was just trying to understand the operations more.

But it is my understanding, that 1s after the player has finished his teleport, that the player.getLocation() object returned has the old world's coordinates, and not the coordinates shown in event.getTo() ?

Is this correct?

So where event.getTo() returned ,x=0.0,y=70.0,z=28.0, we expect player.getLocation() to return the same, yet its still reporting x=-8.189748678030902,y=68.24918707874468,z
=251.82862061288284

Also, does it still withhold a reference to the old player object? I'm wondering if 1.9 changed the behavior of keeping 1 NMS EntityPlayer and not recycling on world change like non player objects do.

**Comment by ProgrammerDan** [comment]
@aikar You opened your comment with an unnecessary critique of my decision to open a new pull instead of salvaging a useless pull. Take it how you will. Your comment was inappropriate and I took offense. I'd be lying if that didn't color the tone of the remainder of my reply.

------------------------------------

Concerning the issue at hand: your understanding is correct, with one clarification: only the World component of the player's Location object as returned by player.getLocation() is immediately updated; the x,y,z is not, causing the disjunction. 

So, player.getLocation().getWorld() returns `world_nether`, but the old x, y, z from `world`. After a few seconds, Bukkit/Spigot updates the x, y, z as well; however WorldBorder's borderguard check is every second and consequentially is mislead by Spigot's failure to update immediately.

> old player object

Sadly I can't comment on the root cause. Your understanding on those matters is for certain of more depth then mine.

**Comment by aikar** [comment]
Found issue, PR'ing to Spigot now.

**Comment by aikar** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/254/overview

**Comment by ProgrammerDan** [comment]
Thank you!

**Comment by Brettflan** [comment]
Awesome, thanks.
From my experience, being the person on a large project who is hunting down and fixing often rather bizarre bugs tends to be a rather thankless task, so: kudos to you, @aikar.

**Comment by cjucoder** [comment]
After using this workaround for almost a week, all of a sudden it wasn't working anymore. My first thought was the host provider rolled back my files, but no, it still was the plugin I edited. No idea what changed, but I was able to get it working again simply by increasing the delay in the timedPlayerExemption from 100 to 140 ticks.

Just thought I'd note this in case someone else runs into the situation.

Thanks to @Brettflan, @aikar and @ProgrammerDan for the work you do.

**Comment by aikar** [comment]
well Spigot is back to its old self with regards to PR's.

Strongly suggest server owners to switch to Paper, where we have this fix.

https://paper.emc.gs

Please give link to anyone who needs this fixed :)

**Comment by WonderDave** [comment]
@aikar Any chance, on the Paper fork, that you can fix the player location problem with End portals in the same way that you fixed it with Nether portals?  I would find that incredibly helpful.  Thanks.

**Comment by ProgrammerDan** [comment]
Anyone know if this issue still expresses in 1.10? I'm about to go through the update steps for my servers ... if it still is a problem I'll re-write this pull to be future-stable under the assumption that Spigot has no intention of fixing or merging in a pull request that offers a fix (considering that lack of interest in aikar's excellent PR). 

Or maybe we should all just switch to PaperSpigot :)

**Comment by WonderDave** [comment]
I've been using PaperSpigot for the past two months, so I haven't been compiling any new Spigot jar files, but I just went ahead and compiled their latest 1.10 version and tried it out.  Yep, the problem still exists with Spigot.  I'm sent to wrong "to" coordinates when I go through nether portals.

Prior to this issue I had been using Spigot for 1.5 years, and the sole reason I switched to PaperSpigot was this very bug that Spigot would not fix.  (Turns out I like PaperSpigot and have no plans to stop using it.)  This was a major Spigot bug that (for me) had a significant impact, and I wasn't willing to stop using the WorldBorder plugin simply because Spigot refused to implement a working fix.  Why they continue to leave an obvious flaw in their code is beyond me.

**Comment by ProgrammerDan** [comment]
@WonderDave Totally agreed, the reluctance to fix (especially when someone else did the work...!) is astounding.

**Comment by ProgrammerDan** [comment]
So, I've gone ahead and updated the tracking to, instead of gracelessly always exempting for X milliseconds, it's now configurable w/ incremental recheck. This allows the setting of a generous max delay -- perhaps two seconds or 40 ticks -- with a recheck every 2 ticks to see if Minecraft has caught up with the player's new world.

The new config parameters are:
* `max-exemption-ticks` -- this is the max time to wait for "catchup" before giving up entirely. 
* `portal-recheck-ticks` -- this is the time to wait between checks. 

Also handles case where tracked player signs off before Minecraft is caught up. Blends fine with existing recheck loop prevention. Smoothly handles rapid re-portal-ing (preventing overlapping checks against different world destinations). This should also work for end portals, although I haven't specifically tested it.

Note that I have no yet confirmed it is still an issue in 1.10; however, this should not interfere with normal functioning of WorldBorder and should be a "safe preventative" if this drift issue re-appears in the future.

**Comment by ProgrammerDan** [comment]
Note: my latest commit has a flaw; I had forgotten myself the exact nature of the problem. Player.getLocation() returns a location with the correct world but incorrect coordinates. I'll address this later tonight, in the meantime don't use commit #116718e if anyone is still following this thread.

**Comment by ProgrammerDan** [comment]
Ok, corrected and tested. From the commit:

This new check routine keeps up the exemption until the player's location is updated to something other then the FROM location of the portal event. 

The Minecraft bug is that the FROM location dominates even in the new world, and only after a delay (which can last for, in some cases, a second or more) is the player's location updated to the portal event TO location.

This check adapts for that, maintaining an exemption until the player's location is updated to something other then the portal event FROM location, or the check period ends. This check will also be satisfied if the player moves (for portals whose location in each world is the same).

I recommend 41 ticks as the check period (2 seconds) and a 4 tick interval between checks.

This works in 1.10 as well, correcting for the Minecraft bug there as well.

**Pull request closed without merging**
