### PR TITLE
V1.9 update

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Addresses #59 and upgrades WorldBorder explicitly to 1.9's Bukkit API.

Concerning #59, basically, it's a synchronization problem. Standard player checks defaulting at 1sec intervals are capturing an "incomplete" transition -- the player world is updated, but their inventory and location are not for, potentially, several seconds. 

While by no means a total fix, I've simply leveraged the "handling player" exemption system already in place to give a grace period of a few seconds post-teleport. 

I've also added an explicit capture for NETHER_PORTAL type events in the general teleportation event listener so that both listeners aren't attempting to handle the same event. 

Feel free to use all or some or none of this code, but I have it in production on my server and it has restored nether travel. I'll report any bugs if they occur and update this pull appropriately.

### CODE REVIEW

**Comment by mibby** [comment]
@ProgrammerDan What about the end portal?

**Comment by ProgrammerDan** [comment]
I haven't tested it. My server uses PrisonPearl and restricts direct travel to the end via portals.

I think this delay will suffice for both cases as this line: https://github.com/Brettflan/WorldBorder/pull/60/commits/3351b251757eebbfdf3cbd181b4430fdbefcc5a1#diff-c21800d11d7445dff8a9147ce4da369cR58
is run regardless of the type of portal event; simply that a portal event has occurred. 

The explicit capture of NETHER_PORTAL type events in the general teleport is just to prevent double-work in that case, but that check could be removed and teleportation would still function as expected because of the timed exclusion line.

In my testing the general teleport event capture AND the portal event capture worked fine in all cases; it was just the "scheduled test" causing all the problems. So, the timedExclusion will fix that.

**Comment by Brettflan** [comment]
I have the pom updated locally to build with Spigot 1.9 from when I was doing some brief testing, but haven't committed it to the repository as there's not yet any benefit to doing so.

You may well be correct that the problem is in the Location stored in the Player object rather than the Location reported in the teleport event. I haven't bothered pinning it down myself, it sounds like you probably have here since you indicate it has taken care of the problem on your server.

Either way, it is absolutely a bug in Spigot which they need to fix. I'd prefer not to put a workaround fix like this in the plugin when it will likely no longer be needed once they fix the bug in Spigot.

I'm also not going to pull this as you've changed the link to my GitHub repository to instead point to yours. I do however like the update to plugin.yml to get the version from pom, that's handy.

**Comment by ProgrammerDan** [comment]
Oh yeah totally. Mostly I wanted people to know that their is hope.

As for the source of the bug, yes -- the point of this pull was to emphatically illustrate that the "bug" is _not_ the actual Bukkit-called events, which are totally fine -- To and From are 100% correct, always -- but the backing _Player_ data, which has inconsistent state tracking / eventual consistency problems. 

I also have a suspicion that this most recent patch may impact this issue,so folks might want to update to latest Bukkit/Spigot and retest if its still an issue: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/90839e6224403fb7f32e6eeba704623a3121d541#CraftBukkit-Patches/0111-Cross-World-Entity-Teleportation.patch

Feel free to close this at your leisure.

**Comment by ProgrammerDan** [comment]
Closing due to undesired pom changes, please refer to #61 instead.

**Pull request closed without merging**
